public class FieldMDTConst {
	public static final String EXCHANGE_RATE_DATE_FIELD = 'Date of exchange rate field';
  	public static final String CURRENCY_FIELD = 'Currency field';
  	public static final String EXCHANGE_RATE_TO_CHF_FIELD = 'Currency to CHF exchange rate field';
	public static final String EXCHANGE_RATE_TO_SGD_FIELD = 'Currency to SGD exchange rate field';
	public static final String EXCHANGE_RATE_TO_GBP_FIELD = 'Currency to GBP exchange rate field';
}